# Generated by Django 5.2.dev20241205110412 on 2024-12-05 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='profile_acount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=320)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=100)),
                ('question_body', models.CharField(max_length=256)),
                ('question_date', models.DateField(auto_now_add=True)),
                ('question_time', models.TimeField(auto_now_add=True)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.category')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.profile_acount')),
            ],
        ),
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_body', models.CharField(max_length=256)),
                ('answer_date', models.DateField(auto_now_add=True)),
                ('answer_time', models.TimeField(auto_now_add=True)),
                ('answer_liked_by', models.ManyToManyField(related_name='liked_answers', to='polls.profile_acount')),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
    ]
