# Generated by Django 5.2.dev20241205110412 on 2024-12-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile_acount',
            new_name='profileAccount',
        ),
    ]
